PORTNAME=	gershwin-gbi-wrapper
DISTVERSION=	20250710
CATEGORIES=	sysutils gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	DBusKit framework for Gershwin
WWW=		https://github.com/gershwin-desktop/gershwin-gbi-wrapper

LICENSE=	GPLv2+

USES=		gershwin
USE_GERSHWIN=	back build

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME=	428e7ad

.include <bsd.port.mk>
