PORTNAME=	gershwin-systempreferences
DISTVERSION=	20250615
CATEGORIES=	deskutils gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	System Preferences application for Gershwin
WWW=		https://github.com/gershwin-os/gershwin-systempreferences

LICENSE=	GPLv2

USES=		gershwin
CONFLICTS=	systempreferences
USE_GERSHWIN=	back build
USE_LDCONFIG=	${GNUSTEP_SYSTEM_LIBRARIES}

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-os
GH_TAGNAME=	758c95c

.include <bsd.port.mk>
