PORTNAME=	version
PORTVERSION=	${PORTPKG_PORTVERSION}
CATEGORIES=	os

MAINTAINER=	ericturgeon@GhostBSD.org
COMMENT=	Update GhostBSD version file

RUN_DEPENDS=	pkg:ports-mgmt/pkg

NO_BUILD=	yes
USES=metaport

.include <bsd.port.pre.mk>

.include "../Makefile.common"
.include <bsd.port.post.mk>
