PORTREVISION=	0
PKGNAMESUFFIX=	-opengles

COMMENT=	OpenGLES renderer for MyGUI

MASTERDIR=	${.CURDIR}/../mygui

MYGUI_RENDERSYSTEM=	8
MYGUI_SUBDIR=		Platforms/OpenGLES/OpenGLESPlatform

USES=		gl localbase
USE_GL=		gl glesv1 glesv2 glu opengl

.include "${MASTERDIR}/Makefile"
