PORTREVISION=	1
PKGNAMESUFFIX=	-opengl

COMMENT=	OpenGL renderer for MyGUI

MASTERDIR=	${.CURDIR}/../mygui

MYGUI_RENDERSYSTEM=	4
MYGUI_SUBDIR=		Platforms/OpenGL/OpenGLPlatform

USES=		gl localbase
USE_GL=		gl glu opengl

.include "${MASTERDIR}/Makefile"
