#!/bin/sh

case "$2" in
    POST-INSTALL)

    # copy xdg
    cp -af /usr/local/share/ghostbsd/xfce-installed-settings/etc/xdg/*   /usr/local/etc/xdg/

    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/xfce4-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/xfce4-terminal 50
    fi
    ;;
esac

exit 0
