PORTNAME=	nkf
PORTVERSION=	0.2.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-gitlab

MAINTAINER=	mfechner@FreeBSD.org
COMMENT=	Ruby extension for Network Kanji Filter
WWW=		https://github.com/ruby/nkf

LICENSE=	BSD2CLAUSE RUBY
LICENSE_COMB=	dual
LICENSE_FILE_BSD2CLAUSE=${WRKSRC}/LICENSE.txt

USES=		gem

PORTSCOUT=	limit:^0\.2\.

.include <bsd.port.mk>
