PORTNAME=	lograge
PORTVERSION=	0.15.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Tame Rails' multi-line logging into a single line per request #'
WWW=		https://github.com/roidrage/lograge

LICENSE=	MIT

RUN_DEPENDS=	rubygem-actionpack81>=4:www/rubygem-actionpack81 \
		rubygem-activesupport81>=4:devel/rubygem-activesupport81 \
		rubygem-railties81>=4:www/rubygem-railties81 \
		rubygem-request_store>=1.0<2:devel/rubygem-request_store

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
