PORTNAME=	xlibre-xf86-input-keyboard
PORTVERSION=	1.9.0
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre keyboard input driver
WWW=		https://github.com/X11Libre/xf86-input-keyboard/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

CONFLICTS_INSTALL=	xf86-input-keyboard

GH_TAGNAME=	94adc53
USES=		xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
