--- pyproject.toml.orig	2026-07-10 13:10:12 UTC
+++ pyproject.toml
@@ -9,7 +9,7 @@ authors = [
 authors = [
     {name = "OpenStack", email = "openstack-discuss@lists.openstack.org"},
 ]
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 requires-python = ">=3.11"
 dynamic = ["version", "dependencies"]
 classifiers = [
