-- Make pyproject.toml compatible with the setuptools version in ports (63.x).
-- Remove unsupported license-files and dependency-groups fields and lower
-- the build-system setuptools requirement to a version that is available.
--- pyproject.toml.orig	2026-07-10 03:47:39 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=77.0.0", "setuptools-scm[toml]"]
+requires = ["setuptools>=61.0", "setuptools-scm[toml]"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -9,7 +9,6 @@ readme = "README.md"
 authors = [{ name = "Brandon T. Willard", email = "brandonwillard+kanren@gmail.com" }]
 description = "Relational programming in Python"
 readme = "README.md"
-license-files = ["LICENSE.txt"]
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Intended Audience :: Science/Research",
@@ -36,12 +35,6 @@ repository = "http://github.com/pythological/kanren"
 
 [project.urls]
 repository = "http://github.com/pythological/kanren"
-
-[dependency-groups]
-test = [
-    "pytest",
-    "sympy",
-]
 
 [tool.setuptools]
 include-package-data = true
