--- pyproject.toml.orig	2026-06-16 20:13:36 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 64"]
+requires = ["setuptools >= 63"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -8,7 +8,7 @@ authors = [{name = "Lennart Regebro", email = "regebro
 readme = "README.rst"
 version = "5.4.1"
 authors = [{name = "Lennart Regebro", email = "regebro@gmail.com"}]
-license = "MIT"
+license = {text = "MIT"}
 keywords = ["timezone"]
 classifiers = [
     "Development Status :: 6 - Mature",
