PORTNAME=	llhttp
PORTVERSION=	0.6.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Ruby bindings for llhttp
WWW=		https://github.com/bryanp/llhttp/tree/main/mri \
		https://github.com/bryanp/llhttp

LICENSE=	MPL20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

.include <bsd.port.mk>
