# cd archivers/engrampa ; sudo make deinstall clean ; cd -
# cd audio/libmatemixer ; sudo make deinstall clean ; cd -
# cd audio/mate-media ; sudo make deinstall clean ; cd -
# cd deskutils/caja-extensions ; sudo make deinstall clean ; cd -
# cd deskutils/mate-notification-daemon ; sudo make deinstall clean ; cd -
# cd deskutils/mate-utils ; sudo make deinstall clean ; cd -
# cd deskutils/mozo ; sudo make deinstall clean ; cd -
# cd devel/mate-common ; sudo make deinstall clean ; cd -
# cd editors/pluma ; sudo make deinstall clean ; cd -
# cd graphics/atril ; sudo make deinstall clean ; cd -
# cd graphics/atril-lite ; sudo make deinstall clean ; cd -
# cd graphics/eom ; sudo make deinstall clean ; cd -
# cd math/mate-calc ; sudo make deinstall clean ; cd -
# cd misc/mate-user-guide ; sudo make deinstall clean ; cd -
# cd net/libmateweather ; sudo make deinstall clean ; cd -
# cd sysutils/mate-control-center ; sudo make deinstall clean ; cd -
# cd sysutils/mate-polkit ; sudo make deinstall clean ; cd -
# cd sysutils/mate-power-manager ; sudo make deinstall clean ; cd -
# cd sysutils/mate-settings-daemon ; sudo make deinstall clean ; cd -
# cd sysutils/mate-system-monitor ; sudo make deinstall clean ; cd -
# cd x11/libmatekbd ; sudo make deinstall clean ; cd -
# cd x11/mate ; sudo make deinstall clean ; cd -
# cd x11/mate-applets ; sudo make deinstall clean ; cd -
# cd x11/mate-base ; sudo make deinstall clean ; cd -
# cd x11/mate-desktop ; sudo make deinstall clean ; cd -
# cd x11/mate-menus ; sudo make deinstall clean ; cd -
# cd x11/mate-panel ; sudo make deinstall clean ; cd -
# cd x11/mate-screensaver ; sudo make deinstall clean ; cd -
# cd x11/mate-session-manager ; sudo make deinstall clean ; cd -
# cd x11/mate-terminal ; sudo make deinstall clean ; cd -
# cd x11-fm/caja ; sudo make deinstall clean ; cd -
# cd x11-themes/mate-icon-theme ; sudo make deinstall clean ; cd -
# cd x11-wm/marco ; sudo make deinstall clean ; cd -
cd x11/ghostbsd-mate ; sudo make deinstall clean ; sudo make install clean ; cd -
