PORTNAME=	cucumber-cucumber-expressions
PORTVERSION=	19.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	19

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Cucumber Expressions for Ruby
WWW=		https://github.com/cucumber/cucumber-expressions/tree/main/ruby

LICENSE=	MIT

RUN_DEPENDS=	rubygem-bigdecimal>=0:math/rubygem-bigdecimal

USES=		gem

NO_ARCH=	yes

PORTSCOUT=	limit:^19\.

.include <bsd.port.mk>
