PORTREVISION=	0
PKGNAMESUFFIX=	-opengl3

COMMENT=	OpenGL3 renderer for MyGUI

MASTERDIR=	${.CURDIR}/../mygui

MYGUI_RENDERSYSTEM=	7
MYGUI_SUBDIR=		Platforms/OpenGL3/OpenGL3Platform

USES=		gl localbase
USE_GL=		gl glu opengl

.include "${MASTERDIR}/Makefile"
