--- pyproject.toml.orig	2026-06-27 16:27:48 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ build-backend = "setuptools.build_meta"
 [build-system]
 build-backend = "setuptools.build_meta"
-requires = ["setuptools>=64", "setuptools_scm>=8"]
+requires = ["setuptools>=61", "setuptools_scm>=8"]
 
 [project]
 authors = [{name = "Radim Rehurek", email = "me@radimrehurek.com"}]
