# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-340/Makefile 549424 2020-09-21 09:05:04Z manu $

DISTVERSION=	340.108
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	2

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-340

.include "${MASTERDIR}/Makefile"
