# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD$

DISTVERSION=	340.108
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	2

MASTERDIR=	${.CURDIR}/../nvidia-driver-390

.include "${MASTERDIR}/Makefile"
PKGNAMESUFFIX=	-340