PORTNAME=	zig2tuple
DISTVERSION=	g20260706
CATEGORIES=	ports-mgmt

MAINTAINER=	kenrap@FreeBSD.org
COMMENT=	Generate ZIG_TUPLE knob for Zig ports
WWW=		https://github.com/kenrap/zig2tuple

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		zig

USE_GITHUB=	yes
GH_ACCOUNT=	kenrap
GH_TAGNAME=	4dbe3ba3516bb9004188e18822c765a0f4fb47d2

PLIST_FILES=	bin/${PORTNAME}

.include <bsd.port.mk>
