PORTNAME=	gershwin-rik-theme
DISTVERSION=	20250710
CATEGORIES=	x11-themes gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	Gershwin Rik theme
WWW=		https://github.com/gershwin-desktop/gershwin-rik-theme

LICENSE=	GPLv2

USES=		gershwin
USE_GERSHWIN=	back build gui

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME=	758a9b5

.include <bsd.port.mk>
