PORTNAME=	gershwin-eau-theme
DISTVERSION=	20260129
CATEGORIES=	x11-themes gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	Gershwin Eau theme
WWW=		https://github.com/gershwin-desktop/gershwin-eau-theme

LICENSE=	GPLv2

USES=		gershwin
USE_GERSHWIN=	back build gui

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME=	4babcb0

.include <bsd.port.mk>
