PORTNAME=	xlibre-xf86-video-nv
PORTVERSION=	2.1.22
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre nv display driver
WWW=		https://github.com/X11Libre/xf86-video-nv/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

CONFLICTS_INSTALL=	xf86-video-nv

GH_TAGNAME=	ca3f59f
USES=		tar:xz xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
