--- Makefile.conf.orig	2026-03-06 10:03:32 UTC
+++ Makefile.conf
@@ -124,34 +124,33 @@ install_shared: scid
 install: $(INSTALL)
 
 install_shared: scid
-	install -m 755 -d "$(SHAREDIR)"
-	cp scid "$(SHAREDIR)"
-	cp *.eco "$(SHAREDIR)"
-	cp -r bitmaps "$(SHAREDIR)"
-	cp -r bitmaps2 "$(SHAREDIR)"
-	cp -r books "$(SHAREDIR)"
-	cp -r html "$(SHAREDIR)"
-	cp -r img "$(SHAREDIR)"
-	cp -r scripts "$(SHAREDIR)"
-	cp -r sounds "$(SHAREDIR)"
-	cp -r tcl "$(SHAREDIR)"
+	install -m 755 -d "$(DESTDIR)$(SHAREDIR)"
+	cp scid "$(DESTDIR)$(SHAREDIR)"
+	cp *.eco "$(DESTDIR)$(SHAREDIR)"
+	cp -r bitmaps "$(DESTDIR)$(SHAREDIR)"
+	cp -r bitmaps2 "$(DESTDIR)$(SHAREDIR)"
+	cp -r books "$(DESTDIR)$(SHAREDIR)"
+	cp -r html "$(DESTDIR)$(SHAREDIR)"
+	cp -r img "$(DESTDIR)$(SHAREDIR)"
+	cp -r scripts "$(DESTDIR)$(SHAREDIR)"
+	cp -r sounds "$(DESTDIR)$(SHAREDIR)"
+	cp -r tcl "$(DESTDIR)$(SHAREDIR)"
 
 install_scid: install_shared
-	install -m 755 -d "$(BINDIR)"
-	ln -sf "$(SHAREDIR)/scid" "$(BINDIR)/scid"
+	install -m 755 -d "$(DESTDIR)$(BINDIR)"
 	@for script in $(SCRIPTS); do \
-		cp "scripts/$$script" "$(BINDIR)"; \
-		chmod +x "$(BINDIR)/$$script"; \
+		cp "scripts/$$script" "$(DESTDIR)$(BINDIR)"; \
+		chmod +x "$(DESTDIR)$(BINDIR)/$$script"; \
 	done
 
 install_engines: all_engines
-	install -m 755 -d "$(SHAREDIR)/engines"
-	install -m 755 -d "$(SHAREDIR)/engines/phalanx-scid"
-	install ./engines/phalanx-scid/phalanx-scid "$(SHAREDIR)/engines/phalanx-scid"
+	install -m 755 -d "$(DESTDIR)$(SHAREDIR)/engines"
+	install -m 755 -d "$(DESTDIR)$(SHAREDIR)/engines/phalanx-scid"
+	install ./engines/phalanx-scid/phalanx-scid "$(DESTDIR)$(SHAREDIR)/engines/phalanx-scid"
 
 uninstall:
-	cd $(BINDIR) && rm -f $(EXECS) $(SCRIPTS)
-	rm -rf $(SHAREDIR)
+	cd $(DESTDIR)$(BINDIR) && rm -f $(EXECS) $(SCRIPTS)
+	rm -rf $(DESTDIR)$(SHAREDIR)
 
 ### To remove object and executable files: type "make clean".
 #
