PORTNAME=	ghostbsd-fonts
PORTVERSION=	1.0
CATEGORIES=	x11-fonts

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Meta port for fonts use by GhostBSD

LICENSE=	OFL11

USES=		metaport

RUN_DEPENDS= noto-emoji>=0:x11-fonts/noto-emoji \
		droid-fonts-ttf>=0:x11-fonts/droid-fonts-ttf \
		font-awesome>=0:x11-fonts/font-awesome \
		fonts-indic>=0:x11-fonts/fonts-indic \
		tlwg-ttf>=0:x11-fonts/tlwg-ttf

.include <bsd.port.mk>
