PORTNAME=	ghostbsd-xfce4
PORTVERSION=	4.16
CATEGORIES=	x11 xfce

MAINTAINER=	goddard1905@gmail.com
COMMENT=	Meta-port for GhostBSD Xfce Desktop Environment

RUN_DEPENDS=	xfwm4:x11-wm/xfce4-wm \
		xfce4-session:x11-wm/xfce4-session \
		xfce4-panel:x11-wm/xfce4-panel \
		xfdesktop:x11-wm/xfce4-desktop \
		xfsettingsd:sysutils/xfce4-settings \
		xfce4-battery-plugin>0:sysutils/xfce4-battery-plugin \
		xfce4-bsdcpufreq-plugin>0:sysutils/xfce4-bsdcpufreq-plugin \
		xfce4-clipman-plugin>0:x11/xfce4-clipman-plugin \
		xfce4-cpugraph-plugin>0:sysutils/xfce4-cpugraph-plugin \
		xfce4-datetime-plugin>0:x11-clocks/xfce4-datetime-plugin \
		xfce4-dev-tools>0:devel/xfce4-dev-tools \
		xfce4-dict-plugin>0:textproc/xfce4-dict-plugin \
		xfce4-diskperf-plugin>0:sysutils/xfce4-diskperf-plugin \
		xfce4-fsguard-plugin>0:sysutils/xfce4-fsguard-plugin \
		xfce4-genmon-plugin>0:sysutils/xfce4-genmon-plugin \
		xfce4-mailwatch-plugin>0:mail/xfce4-mailwatch-plugin \
		xfce4-mount-plugin>0:sysutils/xfce4-mount-plugin \
		xfce4-netload-plugin>0:sysutils/xfce4-netload-plugin \
		xfce4-notifyd>0:deskutils/xfce4-notifyd \
		xfce4-power-manager:sysutils/xfce4-power-manager \
		xfce4-screenshooter-plugin>0:x11/xfce4-screenshooter-plugin \
		xfce4-screensaver:x11/xfce4-screensaver \
		xfce4-smartbookmark-plugin>0:www/xfce4-smartbookmark-plugin \
		xfce4-systemload-plugin>0:sysutils/xfce4-systemload-plugin \
		xfce4-taskmanager:x11/xfce4-taskmanager \
		xfce4-terminal:x11/xfce4-terminal \
		xfce4-timer-plugin>0:x11-clocks/xfce4-timer-plugin \
		xfce4-tumbler>0:deskutils/xfce4-tumbler \
		xfce4-verve-plugin>0:x11/xfce4-verve-plugin \
		xfce4-volumed-pulse:deskutils/xfce4-volumed-pulse \
		xfce4-wavelan-plugin>0:sysutils/xfce4-wavelan-plugin \
		xfce4-weather-plugin>0:misc/xfce4-weather-plugin \
		xfce4-whiskermenu-plugin>0:x11/xfce4-whiskermenu-plugin \
		xfce4-xkb-plugin>0:deskutils/xfce4-xkb-plugin \
		ghostbsd-xfce-settings>0:x11/ghostbsd-xfce-settings \
		xfce4-appfinder:misc/xfce4-appfinder \
		greybird-theme>0:x11-themes/greybird-theme \
		adwaita-icon-theme>0:x11-themes/adwaita-icon-theme \
		mousepad:editors/mousepad \
		xfce4-terminal:x11/xfce4-terminal \
		xfce4-power-manager:sysutils/xfce4-power-manager

USES=		metaport

.include <bsd.port.mk>
