Enable build for older versions of py-setuptools.

--- pyproject.toml.orig	2026-07-06 11:29:33 UTC
+++ pyproject.toml
@@ -4,7 +4,6 @@ requires-python = ">=3.8"
 description = "Sane and flexible OpenAPI 3 schema generation for Django REST framework"
 readme = "README.rst"
 requires-python = ">=3.8"
-license = "BSD-3-Clause"
 authors = [
     {name = "T. Franzel", email = "tfranzel@gmail.com"}
 ]
@@ -57,6 +56,9 @@ Documentation = "https://drf-spectacular.readthedocs.i
 Homepage = "https://github.com/tfranzel/drf-spectacular"
 Source = "https://github.com/tfranzel/drf-spectacular"
 Documentation = "https://drf-spectacular.readthedocs.io"
+
+[project.license]
+text = "BSD-3-Clause"
 
 [tool.setuptools.dynamic]
 version = {attr = "drf_spectacular.__version__"}
