# Created by:	Eric Turgeon ericturgeon@ghostbsd.org
# Date created:	November 11 2013


PORTNAME=	gbi
PORTVERSION=	9.3
PORTREVISION=	0
CATEGORIES=	sysutils
MASTER_SITES=	https://github.com/GhostBSD/${PORTNAME}/archive/

MAINTAINER=	ericturgeon@ghostbsd.org
COMMENT=	GBI is the GhostBSD front end user interface for pc-sysinstall.

LICENSE=	BSD

USE_GITHUB=	yes
GH_ACCOUNT=	GhostBSD

USES =		python
USE_PYTHON=	distutils noflavors
USE_GNOME=	pygobject3

.include <bsd.port.mk>
