# $FreeBSD$

.include "../Makefile.common"

PORTNAME=	kernel-kmod-trigger
PORTVERSION=	${OS_PORTVERSION}
CATEGORIES=	os
PKGNAMEPREFIX=	${OS_PKGNAMEPREFIX}

MAINTAINER=	kmoore@FreeBSD.org
COMMENT=	Metaport for ports kmod to trigger updates with kernel 

USES=	metaport

.include <bsd.port.post.mk>
