PORTNAME=	version_gem
PORTVERSION=	1.1.13
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Introspectable Version module
WWW=		https://version-gem.galtzo.com/ \
		https://github.com/ruby-oauth/version_gem

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
