#!/bin/sh

[ "$2" = 'POST-DEINSTALL' ] || exit 0

# revert to original freebsd schemas
if [ -d /usr/local/share/glib-2.0/schemas ] ; then
     glib-compile-schemas /usr/local/share/glib-2.0/schemas
fi

# removes x-terminal-alternative needed for gksu
if [ -e /usr/local/bin/mate-terminal ] ; then
    update-alternatives --altdir /usr/local/etc/alternatives --remove x-terminal-emulator /usr/local/bin/mate-terminal
fi

# revert original dmrc
if [ -f /usr/local/share/skel/dot.dmrc.ini ] ; then
    mv -f /usr/local/share/skel/dot.dmrc.ini /usr/share/skel/dot.dmrc
    else
    rm -f /usr/share/skel/dot.dmrc
fi

exit 0
