PORTNAME=	gershwin-firefox-wrapper
DISTVERSION=	20250710
CATEGORIES=	www gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	App Wrapper for Firefox
WWW=		https://github.com/gershwin-desktop/gershwin-firefox-wrapper

LICENSE=	BSD3CLAUSE

USES=		gershwin
USE_GERSHWIN=	back build

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME=	dd4643e

MAKE_ARGS+=     GNUSTEP_INSTALLATION_DOMAIN=LOCAL

.include <bsd.port.mk>
