# $FreeBSD$
  
PORTNAME=       zol
PKGNAMESUFFIX=	-kmod-debug

COMMENT=        ZFS on Linux kernel module for FreeBSD with Debugging

PLIST=          ${.CURDIR}/../../sysutils/zol-kmod/pkg-plist
MASTERDIR=      ${.CURDIR}/../../sysutils/zol-kmod

OPTIONS_DEFAULT=DEBUG

.include "${MASTERDIR}/Makefile"
