# $FreeBSD$
  
PORTNAME=       zol
PKGNAMESUFFIX=	-kmod-debug

COMMENT=        ZFS on Linux kernel module for FreeBSD with Debugging

MASTERDIR=      ${.CURDIR}/../../sysutils/zol-kmod

OPTIONS_DEFAULT=DEBUG
KMODTARGET=	zfs-debug.ko

.include "${MASTERDIR}/Makefile"
