PORTNAME=	xlibre-xf86-input-mouse
PORTVERSION=	1.9.3
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre mouse input driver
WWW=		https://github.com/X11Libre/xf86-input-mouse/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

CONFLICTS_INSTALL=	xf86-input-mouse

GH_TAGNAME=	6d84baa
USES=		pathfix xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
