PORTNAME=	gershwin-textedit
DISTVERSION=	20250628
CATEGORIES=	deskutils gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	Gershwin TextEdit for GNUstep
WWW=		https://github.com/gershwin-desktop/gershwin-textedit

LICENSE=	MIT

USES=		gershwin
USE_GERSHWIN=	back build

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME=	7e938a3

.include <bsd.port.mk>
