-- Fix license declaration format and remove build-system dependencies (cmake, cibuildwheel, delocate) that are provided by the ports framework.
--- pyproject.toml.orig	2026-07-09 20:28:30 UTC
+++ pyproject.toml
@@ -2,7 +2,7 @@ description = "Simple package to extract text with coo
 name = "docling-parse"
 version = "7.4.0"
 description = "Simple package to extract text with coordinates from programmatic PDFs"
-license = "MIT"
+license = {text = "MIT"}
 keywords = ["docling", "pdf", "parser"]
 classifiers = [
     "Operating System :: MacOS :: MacOS X",
@@ -40,25 +40,17 @@ requires = [
 
 [build-system]
 requires = [
-    "setuptools>=77.0.3",
-    "pybind11>=2.13.6",
-    "cibuildwheel>=2.19.2,<3.0.0; python_version < '3.11'",
-    "cibuildwheel>=2.19.2,<4.0.0; python_version >= '3.11'",
+    "setuptools>=0",
+    "pybind11>=0",
     "wheel>=0.43.0,<1.0.0",
-    "delocate>=0.11.0,<1.0.0",
-    "cmake>=3.27.0,<4.0.0"
 ]
 build-backend = "setuptools.build_meta"
 
 [dependency-groups]
 build = [
-    "setuptools>=77.0.3",
-    "pybind11>=2.13.6",
-    "cibuildwheel>=2.19.2,<3.0.0; python_version < '3.11'",
-    "cibuildwheel>=2.19.2,<4.0.0; python_version >= '3.11'",
+    "setuptools>=0",
+    "pybind11>=0",
     "wheel>=0.43.0,<1.0.0",
-    "delocate>=0.11.0,<1.0.0",
-    "cmake>=3.27.0,<4.0.0"
 ]
 dev = [
     "pytest>=9.0.3,<10.0.0",
