PORTNAME=	simple-navigation
PORTVERSION=	4.5.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Create navigations for Rails, Sinatra or Padrino applications
WWW=		https://github.com/codeplant/simple-navigation

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-activesupport81>=6.1.0:devel/rubygem-activesupport81 \
		rubygem-json>=0:devel/rubygem-json \
		rubygem-zeitwerk>=0:devel/rubygem-zeitwerk

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
