# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-304/Makefile 549424 2020-09-21 09:05:04Z manu $

DISTVERSION=	304.137
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	8

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-304

.include "${MASTERDIR}/Makefile"
