# $FreeBSD$

DISTVERSION=	390.116
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0
MASTERDIR=	${.CURDIR}/../nvidia-optimus-driver
PKGNAMESUFFIX=	-390

.include "${MASTERDIR}/Makefile"



