PORTNAME=	gershwin-developer
PORTVERSION=	20250712
CATEGORIES=	devel
MASTER_SITES=	# empty
DISTFILES=	# empty
EXTRACT_ONLY=	# empty

MAINTAINER=	jpm820@proton.me
COMMENT=	Metaport for Gershwin development dependencies
WWW=		https://github.com/gershwin-desktop

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${LOCALBASE}/lib/libobjc.so:lang/libobjc2 \
		${LOCALBASE}/lib/libjpeg.so:graphics/jpeg-turbo \
		${LOCALBASE}/lib/libtiff.so:graphics/tiff \
		${LOCALBASE}/lib/libpng.so:graphics/png \
		${LOCALBASE}/bin/magick:graphics/ImageMagick7 \
		${LOCALBASE}/lib/libxml2.so:textproc/libxml2 \
		${LOCALBASE}/lib/libxslt.so:textproc/libxslt \
		${LOCALBASE}/lib/libgnutls.so:security/gnutls \
		${LOCALBASE}/lib/libffi.so:devel/libffi \
		${LOCALBASE}/lib/libicuuc.so:devel/icu \
		${LOCALBASE}/lib/libcairo.so:graphics/cairo \
		${LOCALBASE}/lib/libXft.so:x11-fonts/libXft \
		${LOCALBASE}/sbin/avahi-daemon:net/avahi-app \
		${LOCALBASE}/bin/flite:audio/flite \
		${LOCALBASE}/lib/libXt.so:x11-toolkits/libXt \
		${LOCALBASE}/lib/libportaudio.so:audio/portaudio \
		${LOCALBASE}/bin/gmake:devel/gmake \
		${LOCALBASE}/bin/cmake:devel/cmake \
		${LOCALBASE}/lib/libssl.so:security/openssl \
		${LOCALBASE}/lib/libglut.so:graphics/freeglut \
		${LOCALBASE}/lib/libgif.so:graphics/giflib \
		${LOCALBASE}/lib/libao.so:audio/libao

NO_BUILD=	yes
NO_INSTALL=	yes
NO_MTREE=	yes
NO_ARCH=	yes

do-fetch:
	@${DO_NADA}

do-extract:
	@${DO_NADA}

do-configure:
	@${DO_NADA}

do-build:
	@${DO_NADA}

do-install:
	@${DO_NADA}

.include <bsd.port.mk>
