PORTNAME=	xlibre-xf86-video-mga
PORTVERSION=	2.0.0
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre mga display driver
WWW=		https://github.com/X11Libre/xf86-video-mga/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

CONFLICTS_INSTALL=	xf86-video-mga

GH_TAGNAME=	3f2000a
USES=		xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
