#!/bin/sh

[ "$2" = 'POST-INSTALL' ] || exit 0

  if [ ! -d ${PREFIX}/share/icons/hicolor ] ; then
    gtk-update-icon-cache -f ${PREFIX}/share/icons/hicolor
    mkdir -p ${PREFIX}/share/icons/hicolor
  fi

  # copy icons from ghostbsd dir to hicolor for Glogo in mate panel
  cp -af ${PREFIX}/share/icons/ghostbsd/* ${PREFIX}/share/icons/hicolor

  # update icon cache for hicolor for G logo in panel
  gtk-update-icon-cache -f ${PREFIX}/share/icons/hicolor

exit 0
