BASEPKG_SRCDIR?=	/usr/src

.if exists(${BASEPKG_SRCDIR}/Makefile)
# Get the version from BASEPKG_SRCDIR dynamically
BASEPKG_PORTVERSION!=	stat -f %Sm -t "%Y%m%d%H%M%S" ${BASEPKG_SRCDIR}
.else
IGNORE=	Missing system sources in ${BASEPKG_SRCDIR}
.endif

.if defined(BASEPKG_ABISTRING)
PKG_ABISTRING=	${BASEPKG_ABISTRING}
.endif
