Since we don't have systemd and socket-activated services, we have to start
ifp manually.

Upstream discussion: https://github.com/SSSD/sssd/pull/8649

--- src/examples/sssd-example.conf.orig	2026-06-09 12:32:21 UTC
+++ src/examples/sssd-example.conf
@@ -1,5 +1,5 @@
 [sssd]
-services = nss, pam
+services = nss, pam, ifp
 # SSSD will not start if you do not configure any domains.
 # Add new domain configurations as [domain/<NAME>] sections, and
 # then add the list of domains (in the order you want them to be
