PORTNAME=	bectl
PORTVERSION=	0.5
CATEGORIES=	sysutils
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ericturgeon@ghostbsd.org
COMMENT=	GhostBSD bectl Python module

LICENSE=	BSD2CLAUSE

USES=		python:3.7+
USE_PYTHON=	distutils autoplist

USE_GITHUB=	yes
GH_ACCOUNT=	ghostbsd
GH_PROJECT=	pybectl

.include <bsd.port.mk>
