--- pyproject.toml.orig	2026-06-24 23:25:40 UTC
+++ pyproject.toml
@@ -6,7 +6,7 @@
 # --------------------------------------------------------------------------
 
 [build-system]
-requires = ["setuptools>=77.0.3", "wheel"]
+requires = ["setuptools>=61", "wheel"]
 build-backend = "setuptools.build_meta"
 
 [project]
@@ -15,7 +15,7 @@ description = "Microsoft Corporation Azure App Configu
   { name = "Microsoft Corporation", email = "azpysdkhelp@microsoft.com" },
 ]
 description = "Microsoft Corporation Azure App Configuration Data Client Library for Python"
-license = "MIT"
+license = { text = "MIT" }
 classifiers = [
     "Development Status :: 5 - Production/Stable",
     "Programming Language :: Python",
