PORTNAME=	retriable
PORTVERSION=	3.8.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	3

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple DSL to retry failed code blocks
WWW=		https://github.com/kamui/retriable

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

PORTSCOUT=	limit:^3\.

.include <bsd.port.mk>
