PORTNAME=	auth-sanitizer
PORTVERSION=	0.2.2
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Configurable KV output redaction. Sanitize/filter your secrets
WWW=		https://auth-sanitizer.galtzo.com/ \
		https://github.com/ruby-oauth/auth-sanitizer

LICENSE=	MIT

RUN_DEPENDS=	rubygem-version_gem>=1.1.10<2:devel/rubygem-version_gem

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
