PORTNAME=	cucumber-messages
PORTVERSION=	32.3.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	32

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Protocol Buffer messages for Cucumber
WWW=		https://github.com/cucumber/messages

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

PORTSCOUT=	limit:^32\.

.include <bsd.port.mk>
