PORTNAME=	apps-gorm
DISTVERSION=	20250628
CATEGORIES=	devel gnustep
PKGNAMEPREFIX=	gershwin-

MAINTAINER=	jpm820@proton.me
COMMENT=	Graphical Object Relationship Modeller
WWW=		http://www.gnustep.org/experience/Gorm.html

LICENSE=	GPLv3

USES=		gershwin
CONFLICTS=	gorm
USE_GERSHWIN=	back build gui

USE_GITHUB=	yes
GH_ACCOUNT=	gnustep
GH_TAGNAME=	53a1909

MAKE_ARGS+=     GNUSTEP_INSTALLATION_DOMAIN=LOCAL

.include <bsd.port.mk>
