#!/bin/sh

case "$2" in
    PRE-INSTALL)
    if [ -f ${PKG_PREFIX}/share/ghostbsd/desktop ] ; then
        desktop=`cat ${PKG_PREFIX}/share/ghostbsd/desktop`
    fi

# edit lightdm.conf only if it wasn't already configured by user
# if lightdm.conf is the same with lightdm.conf.sample
    case ${desktop} in
        kde)
        sed -i '' "s@#user-session=default@user-session=plasma@" ${PKG_PREFIX}/etc/lightdm/lightdm.conf
        ;;
        *)
        sed -i '' "s@#user-session=default@user-session=${desktop}@" ${PKG_PREFIX}/etc/lightdm/lightdm.conf
        ;;
    esac
    sed -i '' "s@#greeter-session=example-gtk-gnome@greeter-session=lightdm-gtk-greeter@" ${PKG_PREFIX}/etc/lightdm/lightdm.conf

# edit lightdm-gtk-greeter.conf only if it wasn't already configured by user
# edit only if lightdm-gtk-greeter.conf is the same with lightdm-gtk-greeter.conf.sample
    sed -i '' "s@#indicators=@indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~sound;~power@" ${PKG_PREFIX}/etc/lightdm/lightdm-gtk-greeter.conf
    sed -i '' "s@#background=@background=/usr/local/share/backgrounds/ghostbsd/Arizona_Desert_Monument.jpg@" ${PKG_PREFIX}/etc/lightdm/lightdm-gtk-greeter.conf
    sed -i '' "s@#theme-name=@theme-name=Vimix-Dark@" ${PKG_PREFIX}/etc/lightdm/lightdm-gtk-greeter.conf 
    sed -i '' "s@#icon-theme-name=@icon-theme-name=Vivacious-Colors-Full-Dark@" ${PKG_PREFIX}/etc/lightdm/lightdm-gtk-greeter.conf 
    ;;
    POST-INSTALL)
    echo "Ghstbsd lightdm-gtk-greeter settings configured !"
    ;;
esac

exit 0

