#!/bin/sh

case "$2" in
    PRE-INSTALL)
    if [ -f /usr/local/share/ghostbsd/desktop ] ; then
        desktop=`cat /usr/local/share/ghostbsd/desktop`
    fi
        case ${desktop} in
            kde)
            sed -i '' "s@#user-session=default@user-session=plasma@" /usr/local/etc/lightdm/lightdm.conf
            ;;
            gnome)
            sed -i '' "s@#user-session=default@user-session=gnome-session@" /usr/local/etc/lightdm/lightdm.conf
            ;;
            *)
            sed -i '' "s@#user-session=default@user-session=${desktop}@" /usr/local/etc/lightdm/lightdm.conf
            ;;
        esac
    sed -i '' "s@#greeter-session=example-gtk-gnome@greeter-session=lightdm-gtk-greeter@" /usr/local/etc/lightdm/lightdm.conf

    if [ -f /usr/local/etc/lightdm/lightdm-gtk-greeter.conf ] ; then
            echo "indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~sound;~power" >> /usr/local/etc/lightdm/lightdm-gtk-greeter.conf
            echo "background=/usr/local/share/backgrounds/ghostbsd/Arizona_Desert_Monument.jpg" >> /usr/local/etc/lightdm/lightdm-gtk-greeter.conf
            echo "theme-name=Vimix-Dark" >> /usr/local/etc/lightdm/lightdm-gtk-greeter.conf
            echo -e "icon-theme-name=Vivacious-Colors-Full-Dark\n" >> /usr/local/etc/lightdm/lightdm-gtk-greeter.conf
    fi
    ;;
    POST-INSTALL)
    echo "Ghstbsd lightdm-gtk-greeter settings configured !"
    ;;
esac

exit 0

    ;;
