PORTNAME=	xlibre-xf86-video-vesa
PORTVERSION=	2.5.0
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre vesa display driver
WWW=		https://githhub.com/X11Libre/xf86-video-vesa

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

CONFLICTS_INSTALL=	xf86-video-vesa

GH_TAGNAME=	5b33e95
USES=		xlibre-cat:driver

GNU_CONFIGURE_MANPREFIX=${PREFIX}/share

.include <bsd.port.mk>
