PORTNAME=	xlibre-xf86-video-dummy
PORTVERSION=	0.3.8
CATEGORIES=	x11-drivers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	XLibre dummy display driver
WWW=		https://github.com/X11Libre/xf86-video-dummy/

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

CONFLICTS_INSTALL=	xf86-video-dummy

GH_TAGNAME=	dd676a9
USES=		xlibre-cat:driver

.include <bsd.port.mk>
