CARGO_CRATES=	autocfg-1.5.0 \
		heck-0.5.0 \
		indoc-2.0.7 \
		libc-0.2.182 \
		memchr-2.8.0 \
		memoffset-0.9.1 \
		once_cell-1.21.3 \
		portable-atomic-1.13.1 \
		proc-macro2-1.0.106 \
		pyo3-0.27.2 \
		pyo3-build-config-0.27.2 \
		pyo3-ffi-0.27.2 \
		pyo3-macros-0.27.2 \
		pyo3-macros-backend-0.27.2 \
		quote-1.0.44 \
		rustversion-1.0.22 \
		similar-2.7.0 \
		syn-2.0.116 \
		target-lexicon-0.13.5 \
		unicode-ident-1.0.24 \
		unindent-0.2.4
