PORTNAME=	cucumber-tag-expressions
PORTVERSION=	9.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	9

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Cucumber tag expressions for Ruby
WWW=		https://github.com/cucumber/tag-expressions

LICENSE=	MIT

USES=		gem

NO_ARCH=	yes

PORTSCOUT=	limit:^9\.

.include <bsd.port.mk>
