# Created by: Alexey Dokuchaev <danfe@FreeBSD.org>
# $FreeBSD: head/x11/nvidia-driver-390/Makefile 563994 2021-02-04 06:00:04Z danfe $

DISTVERSION=	390.141
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	0

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-390

.include "${MASTERDIR}/Makefile"
