#!/bin/sh
doas_settings()
{
    if [ ! -e ${PKG_PREFIX}/etc/doas.conf ] ; then
        touch ${PKG_PREFIX}/etc/doas.conf
    fi

    grep -q 'permit nopass keepenv root' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit nopass keepenv root' >> ${PKG_PREFIX}/etc/doas.conf
    fi
    grep -q 'permit :wheel' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit :wheel' >> ${PKG_PREFIX}/etc/doas.conf
    fi
    grep -q 'permit nopass keepenv :wheel cmd netcardmgr' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit nopass keepenv :wheel cmd netcardmgr' >> ${PKG_PREFIX}/etc/doas.conf
    fi
    grep -q 'permit nopass keepenv :wheel cmd ifconfig' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit nopass keepenv :wheel cmd ifconfig' >> ${PKG_PREFIX}/etc/doas.conf
    fi
    grep -q 'permit nopass keepenv :wheel cmd service' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit nopass keepenv :wheel cmd service' >> ${PKG_PREFIX}/etc/doas.conf
    fi
    grep -q 'permit nopass keepenv :wheel cmd rc-service' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit nopass keepenv :wheel cmd rc-service' >> ${PKG_PREFIX}/etc/doas.conf
    fi
    grep -q 'permit nopass keepenv :wheel cmd wpa_supplicant' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit nopass keepenv :wheel cmd wpa_supplicant' >> ${PKG_PREFIX}/etc/doas.conf
    fi
    grep -q 'permit nopass keepenv :wheel cmd killall wpa_supplicant' ${PKG_PREFIX}/etc/doas.conf 2>/dev/null
    if [ $? -ne 0 ] ; then
        echo 'permit nopass keepenv :wheel cmd killall wpa_supplicant' >> ${PKG_PREFIX}/etc/doas.conf
    fi
}

case "$2" in
    POST-INSTALL)
    # backup old files from FreeBSD base system
    doas_settings
    ;;
    *)
    ;;
esac

exit 0