#!/bin/sh


case "$2" in
    PRE-INSTALL)
    if [ -f ${PKG_PREFIX}/share/ghostbsd/desktop ] ; then
        desktop=`cat ${PKG_PREFIX}/share/ghostbsd/desktop`
    fi
# edit lightdm.conf only if it wasn't already configured by user
# if lightdm.conf is the same with lightdm.conf.sample
        case ${desktop} in
            kde)
            sed -i '' "s@#user-session=default@user-session=plasma@" ${PKG_PREFIX}/etc/lightdm/lightdm.conf
            ;;
            *)
            sed -i '' "s@#user-session=default@user-session=${desktop}@" ${PKG_PREFIX}/etc/lightdm/lightdm.conf
            ;;
        esac 
    sed -i '' "s@#greeter-session=example-gtk-gnome@greeter-session=slick-greeter@" ${PKG_PREFIX}/etc/lightdm/lightdm.conf
    ;;
    POST-INSTALL)
    echo "GhostBSD slick greeter settings configured !"
    ;;
esac

exit 0
