--- pyproject.toml.orig	2026-07-12 02:08:04 UTC
+++ pyproject.toml
@@ -234,7 +234,7 @@ healthcheck = [
 ]
 
 [build-system]
-requires = ["maturin==1.9.4"]
+requires = ["maturin>=1.9.4"]
 build-backend = "maturin"
 
 [tool.maturin]
